apiVersion: apps/v1
kind: Deployment 
metadata:
  name: gcp-devops-deployment
  namespace: gcp-devops-prod
spec:
  replicas: 3
  selector: 
    matchLabels: 
      app: devops
  template:
    metadata:
      labels:
        app: devops
    spec:
      containers:
      - name: gcp-devops-deployment
        image: docker.io/kubeje2/hello-py
        ports:
        - containerPort: 5000
        env:
        - name: PORT
          value: "5000"
---
apiVersion: v1
kind: Service
metadata:
  name: gcp-devops-service
  namespace: gcp-devops-prod
  labels: 
    app.kubernetes.io/managed-by: gcp-cloud-build
spec:
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000
  selector:
    app: devops
  type: LoadBalancer 